export const LOADING = {
  SHOWLOADING: 'SHOWLOADING',
  HIDELOADING: 'HIDELOADING',
}

export const APP = {
  UPDATE_STATE: 'APP_UPDATE_STATE',
  QUERY_OPERATOR_DETAIL_AND_AUTH: 'APP_QUERY_OPERATOR_DETAIL_AND_AUTH',
}
